services:
  web:
    # build: .
    image: dairoot/chatgpt-mirror:latest

    env_file:
      - .env
    environment:
      - CHATGPT_GATEWAY_URL=http://gateway:8787
    ports:
      - "50002:50002"
    # depends_on:
    #   - gateway
    volumes:
      - chatgpt_mirror_db:/app/backend/db/
      - ./backend/logs:/app/backend/logs

    restart: always

  gateway:
    image: dairoot/chatgpt-gateway:latest
    # ports:
    #   - "8787:8787"
    deploy:
      replicas: 1 # 账号数量多时可+1
    env_file:
      - .env
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    restart: always
    # ports:
    #   - "127.0.0.1:6379:6379"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 10800 web gateway

volumes:
  chatgpt_mirror_db:
